---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-env-prod
  namespace: renovate
spec:
  encryptedData:
    GITHUB_COM_TOKEN: AgCXGc3NKBpexT6gCqQyw66FfgMoFepDY3337v4TuTdY5c1aM246uZGPsGO3Ts8fBva7MwcWvVXZyxlPCOrVGMOgCchhezx/TroYm+Kx6O9RKxPksY6OEGjY7Dt7gOKX7GqahUaQ2powmfG3GFMG3NQmoGDteBpSqa/p8jpVCZ8P9wcyqF19lJjQtSys/3bMfVUVh6911CDLCgGxrsyK3OqUaFT91XlJxudd113l6VmO/IfzDoxlsOZQ/wmVMsjwZv2mNlzVzrx+moqoQpWCx1bwUzaw7OZqZhzKKGsf+OIGtqmCcW5aJPI/I27N+b6ZtdEjk+tNfvrGczvDRP4Xl38BCCIRByY6hgKOoV0nheXRvveJ7W8pVVoht6mA0XY93TjSt87T0uXlaURlgTSXK0SwHwnegE9WUSMXItY2/8A1QOOVlcbgoia/rOcxGTrGKIpOimla8mks9+qYdsrCXT493pUYVgQITgm8dxq+ZZ/y6DjNDjBkQOPLguBfF+1Z6xC0j9TVyS/0x1SOGfI1k1iG0MrV0y0lFNu9HP3NQ5YfQ+1kpXZ+qOZA1c5qQhQMbyAa8J/x90ZjI6Sbv/AXa7kqbuv/6qOxkXVDKZgrEaMyFu4oec58ovr1inC7pfd4/Mtg9AIZXtwikb57d4gVymOoTnToCsK561zCylPq5lw1yZ46kd5BI5cQvCvJo0iv8Y6+DEuLVaKuWBgy4PmEylAXC/slp9VK3Rbu84xpsBl+SFCJKKkzZAvW
    RENOVATE_TOKEN: AgCq0IVDPA4VnbGhx9Bp9fAUGY1Fg2WocrxRMZOQX9PvUL2TwK34/5RiadwJBYfp8JSZ0LAytz3NnwPMTEfQAUX8l7p7xyToBLURp57NKec+Aa6K0qqbFei7RQ/fAzCAFimJD5KMhU14FYwDqXnkXwag3ejwHTkY0qanxyPblgp9sqTFvCrgTvwCTS2YD2fZ2fBtvaeTG3STkPlMgx/PPp8V6qlRlRFXVMFJpBiE2FjEBgxVpTHHKTAUdsLUd5riHh9TCG+RH6GSkyc+BanForjrYue1yvxiOOBKxhfEju20YgPfE22MERkdhN7QwgZNu8zuyaaaOCkmYfhRLzU01g3JacjpW+AAA1maYQKMdze94zTliUF/PCEDf/sSVt+xubFJpIosNic3lgmA2IElInta8EFI6vazq7eOpbJ0KC+LatKaP6HhegYvijCSfW/CKe0oHmOE5NRzRCfZKZq9Yg08ziEQbdxnrCy77cFRtY5TvnlzusvSlvkhnBVJl+5xcXjS/V5GIhJfkr05NNwDMmd/YPsXkIRaZzpQsK4tj80YM0+ek4MzXDkSOZUBPAiTqpcfw8WGL1WVCUW5iwTUnGKLcrKL9SwMFIur1bYteX6IKpPiwuW9Z3n/bHwfXH83muA90S9B1W/B9mMYhZ9jogYuqG/IO3U9G3P+X4qOH9FARMcwSioAz3CNM+nhWzgb/UBz0Lp/1QmUB1y1mR2kHVxkWx4mXy127XRtKaJwv5XWLsApVAHzhBVa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: renovate
      name: renovate-env-prod
      namespace: renovate
