---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBpttfuAZFG0mV4gFjAjuJ2SpPKLeAhsvES81RQ5wekfJl9Z4rbGSZNelr3B1uHGkdvt4piMeRynGlkzDCQW63AAJeT9R7ohlXE8D2aoxDc4FeJKmr30FAsanPtz1gjZS494BkaDXKsFQM3OVr8ZjWXwmnFb98k5Ep+5VdRD2GwuPYR+IAI4uWjguWddwXHYzO6gDx7S8gEB44jIBuB+wvIRVE7COQh+n8hf4CO5x/td3AVX0pu162LZVuzl8AF8bkaBDQWan1NUEfCxk+ot1OYzBUHxkg0pd1Acg/dkoahhjOoS6/hR4LRUEfw9VPhmiJ/tRCzzm4ShFkJrf9vwm8a3hy6kuPPbdEXdT8ZDeuYHXRrhsffBvda5BvEZGVfWc3xzB93IEDz6L43+0peAVyeUU2oVF0UFs+YurkSbyVumqNKgvx+Sps1qaWfbo/lR+ZMu/5HVUevUgxUnmP2pg99/W1yVtqQkHDV/DU+SEb/P3op2cqG/TJEJou0YEV8w4IRVcToA8lPl0icsxQ3ENdrvewju6aoOR1e/P6T7w6d5K420TyPhVUj+kBeVAnm9fEmYuW3KDypCqoVS7fvtxbC/fSZfrDEPtZBoB3g7XLuRfpPygFbklJO7DPNpDlMd5AIxXfTllQB2LHC+z1ck333QXTjnJneZu4N9LUrED4+1lpAekLsmsJhf/eqwFNgARiuR//yF9tLdj0OShoF+ZYCU2+QfWIw/RmRn7bHZjpjRjrpVOuvGJXK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: cert-manager
      name: cloudflare-api-key
      namespace: cert-manager
