---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: launch-forgejo-runner-ci-credentials
  namespace: launch-forgejo-runners
spec:
  encryptedData:
    token: AgC3PFoiYGJxhPPzpBL20B4VRW5TDTxBduNi+w3rwG4yIimS4+q6Kc9zL+tist5Onz00qzilSooJ4xT7++gq2VyJK+7Ghtca4oanL1PfP0KVmpvBM1w6VBTUMhzjU7ulZZp/e86FfHclwpTZ8zQSuzaU6kr+5TuUPGpeGYDhHb7VtUNGyuyXu+3/RKl7O3CJznfdPegUzIP29Qb8mbtnCLsrvlW/r95yjZLuQ2BNTotcY0507gHE8GKNAq4hjdt9baRMdZIiHADP/D3/fYOZ11ey5FDMCnkG6btKrDKeDkdlCWude0QgVKkeyCNSS/ydRaO4JOhxB2vIk7k1ke6psGjBIFwv2fv6k85iNb41arTuJXVIZam8ZVUUUFqalM3IN8/Tfl/nfb9Skln+ksUJjB3oVsgiQ5ejEIUFDPem1yH0yVH8XgigvchbEm7Ukko6cEEAN9yAOL9P6xcO5YukcqGmWrxOeprsD94Zy6HFUdoL1YjEeiUaUvxvdJYqijkI9e0q1KNsj482Fo4GhggTuxLYnQcGmWdB0lohNPxQ4zcUXGrr3FRph8kxGa68w+0jXOLkvvGF7CnpE1TZ56jp0wYCQIXvSh2s5ix9Ha/FlH61k+DlmK07lGo7D+ufUoq73I4BvB0Qk5aBk6nX+/GRbcxq8t3shlHWwu6bqsQdHJjWB06oe9RwL3tnIBePCvX+Suu54BM6oFAvLxZTy2Hu+1D/TO08cCpCSqmU+UeGCLaFxLG0e6448xGu
    uuid: AgBLVa5a+5GGYzR6nUAMQFdk3uVT7/e0T4iO+TrCFrnsCsUgrm5XIrypE6Ho+eDztTr3OZi8jTkP5ri8KX4vQb7J2jHZQ1V4sBMEz/W34XEs9TFDcq4BhPsO4NsynSDPCR8r0Frd19k3HsIGqPYTvZsvDfzX/4pRl8yQ2iSetXCvNbjGRJlQbNqxzYa/zMTA0IGDenazhpBtOhHE7T/64cprIm8CU26ymbK/LgCPK7NLa48aA4R/uy2ohHPr3zPeKOZSUSC+N1BNvmzl3OpEqcxC6SO1RQ3OL8zufBp7lUxffiw5ZtYOGwYLI5bKRvjcjqI3GU6UgYOqxBomOGIKW3dctFbQc6pE+jO3fJtmRMhbOuVxKHCDGthJRBAmBFiOJ4lChFqa4pbTqW4E5Qfa43y4MfIAR/VK6J0ptYOwzOSx9c17tkb17ITUW/JvYKtv0xyFkwM422TJAB4WMIP6o1z7Xvv2UjU6/mQioa2EPIiR/wTxVzKB49qCX31FqCAgvFTZU2VvsucV55r7Jlx0PRRINPQBhl6XkAGzLq1gY6PFdUmUJja6jhn/nt+KHL8g9E5/Ntj8ZorZwtaUVmoDOY3VZl2PEarO7JXAKo9VhtGDh05Q3IsJ6qRN9zmRoFXeGbXMaKDagZsq/oFrgmFpLxweH2vbE+/Ca+zSfSJfx4vaemWcFTfDPDYyU7WQNnTnJedDGHTMGaTpGgSVYt7ZXpmwHOfdNO70VG9B384tPPKoxrUN1PI=
  template:
    metadata:
      name: launch-forgejo-runner-ci-credentials
      namespace: launch-forgejo-runners
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: launch-forgejo-runner-builder-credentials
  namespace: launch-forgejo-runners
spec:
  encryptedData:
    token: AgAhiLUhWVKjBfa9XvC4ACz6lhY/QNZf2yHsUByjHouQsl539i4TD2vRygtLBpt8vMfkxS3gc4yO5mX/Jgv+VvXosCp+D6NfG8MU1WT/r0LvH/ACS3sUJwX2xoK0wv6Lj95SCFKY829kmPHY1IowAdi3UbtJkfba0ox64XvCInzC8yhA6JecWlvdxMpEV+nqzfMaBW0XUodJnSr+lxmKNWQYQXQf0zoGgka5z0yhVa6JS17RDpNiBUwEFgMu5OKQwAlQDlS0cDxWYQqYSAwzsflFt6E4/f3+zVxCjnEMZh7/y5AaLh0bYNlhRQ2UNYFO+LADecRFfiMpyfii6bdacBaP/D1qEvt83YQ8mGMteNB74zJVJWGk5geO0iHcK5mSYmDs4JJFYQGnvSVcLetBAdVb0k62sJHVW27hEdnlZFR2kTHDNgh79D58Aj4DYXfE+i92d9CDg37X8kwMOFznMBuqD+0/TBbZlJ1/iIyf+ojhdEoN4DFZawXbiAIp9rDWZ2TUGnGxk0p2+QMyUleAmOmhf1ppa72wrgqpGSNJJcI8N3DtDmB843SRqNPrDVF0PHO3RnAW43wGf3JBBk9b60u1UNLExl922pNnc+5jekQm0gZNJDjYPKwlzxSKzsXmJ7/+JkFjz1KLpYOE7unHKpkQdZZcLK+SkgJPthbDLruUOkrVgLgoVXjAd4fKG3ZfYBz7hwe5inx2V0E8bqbFRNKdOItl5tT+RbTLKdxHyL1ADHzQQEfvm1Ld
    uuid: AgATn1z96jgfAMrhlJl+rG+h2GF4HMPt7tQnD7YHXP67izAvrVEjgyvwEmuGN1PaHWmRhig43yMmtFRjB5w7RoRTxwkedqZbc13zpIBbkrFfoOEkUagDA+Lt7+buz3z3zdRI4CVY3DLIXy/Lg/fGuis+o4vcOdXdjc+msxIGULpgXKi3LM9HNQViAuGfKKBQLW+Fz5ZXW0p9ifNSDjAcCP/cHZL52fjH4xBW49zOb13SV5rHKqlwfmxlqWjLKHNTTWjtKhx8a7vdsLLLkouHzDkCBxh/AsD/WeX4H5roeSCRlhIQ/jAXweeYUsAs4KoYYDoGgXF7K/ZU9vTZre2yzAp+5JWJXgHeW5GsQwGVNZIW89CYiWWy4aKYY4POfr8uxXxxFYn6/ngj4zfxEz3ab8JjSyrL56gxx+DNtsqwdb+kr9Dv43oSE/L5mp+IHCX1PFjwZ6NYxyUWbytUMiSsP1Sp6/mQC8yAx+Q7a7+MAH4wO3INQ6LwbpuuenAw/B4TW1hUWJXbR0cLdW8DmKqSbPFNYfYmv0xOcFXktNHOmJz9NCbPMm1mtDsAy4B/2fYV6NO2LcdeN9BmqEVe0Ip2VmYyeASxdLLkOkdPT2EE9q3CRL95oIh2Y+yjfglQl6FEnGb4z/VzUEKvlhP7BzCGFEIqrFXNsd5tC63DVV54CRBs6hzlm+AgygszpNDaziIDFOV+Qq5+H1PinBbLPk3qk+K8JiyLZINNn495UjNW0SAiWG5802w=
  template:
    metadata:
      name: launch-forgejo-runner-builder-credentials
      namespace: launch-forgejo-runners
    type: Opaque
