---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-validate-token
  namespace: forgejo-runners
spec:
  encryptedData:
    token: AgC1sc/q5Rslzno58BTu3y3Z+cdhGuBUkk/L38iAD8T4+qTvzBVx8vpWiMs6EHS4JWDESDoZf/b0jEAhP7emInQCpkgN2RA6ZL4fe/+Io244rG6m8pYItLOd1yP2/Dei+WB7JP2f0R8RgyR1bGz/YX/LKZdicvjEwrt7ZfPxEuc3bEYMX5eSRAuYli2XhJI5Wr8UNULxymWBiuuJ+HKB7/ZqrOIzq3qaSQNj7ouwlvIPl7KuS467Fta0TtJIHjAgmoTD93POsY4teH3jA1a4oHQNWDDNvCfxZiRf9noc697E/61w2rl3r9qNEju+Uat9CSmVg0nocPacDYQbWAijgN1qtKd28urPPdX47xmBFzjR0YgMo8T5ujnhcsShP2BJlXMNw29f7ei66nlGYEGSzljTO1DLDJ8X/hEnLmkvLxndX40brDMAnou6OW50UHsCGDuFQ7OO4jDrCwQqqT+fglIAJj1gUhwXeDZscffUdgbfumIgpl9AoCfmKepZsdkgMTJppccQJ1Ach7p5/F/gKKgP+4TS0JcCPZ4zop8cVlPZBhnnQACevB8rBHSvHIfvqfL5HVO+Cp/aml8D6MCbglzf82p8Pg6rvDZRngCshAZDdLuwwhFG6CIjE2S5HobJDPLNX/kvyXI9cYglnxIgJOgJO9vNvORpRURvuNvUGlQCxVHyo66hlf7Ba8f6ZDSaAbj/8qrch4GS2XgtgUTGAJKbO1X9BzoZDkC7yLg2yMVCGmGgETke1LfZ
  template:
    metadata:
      name: forgejo-runner-validate-token
      namespace: forgejo-runners
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-builder-token
  namespace: forgejo-runners
spec:
  encryptedData:
    token: AgA7DVm6mu/NxQvKJcOATpellHCyYQHOifanWaxMbigy66yauRz31OlrKqtJBLGJOaYcoLQjKvPspcLTw4blAWlc4zKb9MbJ39g46VPOCdmTQ6WMqc0B3zroTasbkQ+vhXoRSQSXwmaHlwGjdlvC8/mmGPWxDSgJk38GEqMa4tmgC0/8kicm4tX7dx7+VcBbjjSwPK1Ed1Xn9sd6dCmwt1OTulU8RQk++1XKcDS2THCBzggnLuLWYwFgmjXNEf4wyivJKynDaEpoJifUzM5WGsGmkcmhuH2yb/esgnBQb9gS1cpdG49ynfOWY+2cO5cPGg1lTXcwUSLvmeYAjTookjXKJGYFBbjYKAjkE39waDjVKk0vfQ4kQiWnl9jWcD/Q2I6tfsusCu3gdQD6aQhT8IkcviuN/zGJF7vDR2nthAwbQyBgMhNYwMyfJ1yn4W4QQyk3JTBRpOH2lwEmTD/6sMOgI2eDHuVZprzuADe1Z4ajKx+iVXICiedtkEaOuP8+a64ciAGbAOeUbqjeqUpnA+ULiV7jYPX7xlTouGBuqb3MREfk8p5539OrhdIrvj+NuZ6Xu6OqqpJ8kK4EEQifwEo/nLnlXMaK2xzwErBugvrIFAABnkkMYM8BCaWErLHeE4ItuceNf9kDD8kDHcbnXGMTcPKSh+sdqVOmrbARB/jzv1XZSMuoQwNSFRIkxeD3j4zL0gNpVLHVyvtv0TQ7LXB0EtUkIqhjbbnyrjvXsqk4m6GWoZW9y8YF
  template:
    metadata:
      name: forgejo-runner-builder-token
      namespace: forgejo-runners
    type: Opaque
