---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-validate-credentials
  namespace: forgejo-runners
spec:
  encryptedData:
    token: AgAh9+immhnaSqqjTVA6vUYW6P6+i/GxPwnzLZbc4S6ZEy54AEW2akHJ4DW6Ak50Lbj763+G5ujPBgn+gQ/rhWOzbysjG2VgxiRf/ZPTr3J9XX8rdSmGMiR03gynJ3sqVmkY4RFQJx7X9wJwGoAd0citsgpL0QriwcFS+qNSLeKKtCMueE/lCpt9k6mE3UuV8x58eSKuYerMmZLFXhFfOPyCGnci16Yh197+lVyM2afx3PjUlfMqDdAAad69U6SdXAjl3/irQLFeIpdc5Y2CCUdXt4TLF3eZKWvp97KzapX3GfBIki7IK2e44V/TGmVCRjL6Rr7E11vQZHCYCbcJwZuBo0T+Wjk8FvjTkEDh4AUSUtkKibIA7JYPKKX0Ipvr8DAEk9h4SgyYizVDhqjvG5Pw1T1WrcsywdkqdAu8iSC6rlj7sjAU2jrTmWxHL6VyW99Eti6m0OywGm+Ujq/IJZ4rdZ6XxkI7biokyejAkedtJlgl2H14jgk1bl9H/x7jMgtjnHDaHNem+ihrp4HonH+5I+P8lnGITwK525GLwoKPjobRHGsIigXQnXR7lqvYbjyBmSHKQeBmoT68xMnCbn83KSKkFdbOYsnrloq4S7b5MzPSR3tV6TkamDK8P0vMdrS0OUD7684BTc6jADtIYrSfw2ZndQfYKVXXnBZy6d/1BhnR+GCSWUuhdf+HXibujE+TgUe7pSVhyF3vh962SyfC3kfK0Iuei4W/wOcxA8rXC9vub4N6R1S6
    uuid: AgAjMI1Fva/LqQ47ArfUQR06kamRACT0axqUQ1lRqorT5Cbi54vz7MIamCmal3GjgY/8ilgK3RGo+sNjansalZzEsyTFIP3ZD2ld6KkmKsZ8BQ9hcD/tlmGPhJoNH1oOGoF35dMmC7H2vy7MA1b/sIGOCE0fybBbzcAWNYHd2UDS0TQdeOKYK72yiNV0w9l5DGJPQ492RuQ+CKfa8/nJ4qdZN1Afa7QjvQzTIN98KhAey78H5AojHrHc0y1o/pg6RXQP2uRhVAFpA/tKleI7mcytdfLTVO8vJIcP7qC8Kpl7E1CMgIDlq2RQuXqx+3oEqWjauErErh1o7yWfNCVd7USMhv5bqxUfVLLy7LSAa8AvtGnj2TMytr812obMgQn3OCgkOyUs1oV10/3+lSaoy7uzN8msrxZX9GzCHIZr6w5kHPgP6rDsc/bJDxksvCvGK61HbMrZsn/WoOpq0s6Ln2EhQISHt35G44OaGBvSgy8TKgIUS7/VCbJoDc19j2R+vUoFe9O1WYDDV/vlnyUI//c1Z/VwlDdT5wYsNuEwBm5vPe8WMFSkysOWo2PssljVQucN612IWdsmxPtIWfbQ2QndNKeFeW/VGc98w/MZPUh7B0OsKkenM3/zSfhS32T6ghVauBJCxhEI2fMjwvbo4LgXJKKUZ13TVE69D/AqBlJMH0a0+4C951gA20IY2gFSXwFY3dp4GZLKHpKj+VOrCe03QRco1HEyXiAxj1wxgYX699SFb50=
  template:
    metadata:
      name: forgejo-runner-validate-credentials
      namespace: forgejo-runners
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-builder-credentials
  namespace: forgejo-runners
spec:
  encryptedData:
    token: AgAismJye8XL59ByezLlmzxSOijMPNJU5OGLqgjxLycEHDTvhpEN1hqjZjj6h4Jw7MKp0KHFOCnGxnw81AeYTlinAtGm0yk491g871oe/MK6bLX1aSYTIsgN/lvwXpYr3byzx4ht3mcSVne26K8gBe5VnBNu73YZQvYAXBsK4I7oqHdhgIqZKx9V0DeMS+Ey8tghU8DzOVJoGqS30qLcaOWzZKWNr+8ZSWZrLy0Rpx6wx1/3aQRWctkzHo0biD2haXPGpBwclpbGDIcJ2skmrhMnDkot9L0iJtyU8k8xPbh+i5fwz1nmcG/lxuXl65OvGuw/kDxcMlSK1RRkuNy4x+pVtKI/OmvPjgeJdVDJkNQpbSBEQC4eqTCarwQ7cwBgTka5tL+LX5g/pUF+WSumYUMAbMH0usoKSKFJARqF0MaIUbydIl4amhd8B4z921bAy5BhAwTn8PsyySanJVR61kCbbhKJaPMzcY+Roix6iAr1cv9Jl+2a2M9kL9I+TaMUX+b2yw9dkDtRQi7tuYDFzQIWws/xr/r3zxoiFZX3sj/H5Y17u1Ug+x1y5GXF80HsWL9SOi8WgILOKazqrYAkVhxbEQODHMLXilEtBX8zydmEoAsbR/NupCnCizh5kHC6VIC2fOC0iceK6/zHRB7kkKdxOhN6P5Rn2YznfKO7HQVmtDkqdFbN3dYv++CzGKtYUIKfG4I1rM7mT/80Vr7GVzTgv7f7s+7+HbCQXQckSg71gly52LuTvLxA
    uuid: AgC855e25hntllNorWlWfLBxeUOH1C9SIe2lfvuAw2Q+WcgH3+DVF4UoCrK1gytHdj8txWKsgzKrV+hmaqQaaLiDyLyf0sEN8EDiO8IrLm23zwc1F0OtWvZVZCQst/uriBmE7/ZETWl4So17+3SpE8ofahw78dMvLVsW2oESj4cocBFgTvW67P/eiE6rU7XkJdk2st96qmppa3b/G7Eoon4jfC3w/bg50aRsbwlOOMdK/qcHdHrK9lKprDmC2JTzb4y64N3glPK0IQMHAz1XYDUIIqn0XjHM+VzM1rwLlUoirXD1bbHEPwYjapcriGzd5wwdFmHgubxDl7gfpHoX3NAmWsAeOR30y9oZsBWCU4tGtoM5vUx2dRTn+oCy4fmlXX4KGKxzuyGvnvvAYNjslANywnCcw7vdyCTC/NEtMlpKHhkHq9Me5C9QTHsDGntkbypOr/SXNVvmhOIzgIwVm+sZG+tNur/G0zcBYDToufp41gp448IU36TjiifHI5RV1o4Ss6i8eVR4FeGEvxkzB4puwpI2pabaY9GU/gcq4b4r2vmO6GwP+RhrQIxepToN/MIJkQH5wjPN+qrjjcYutpUwk4Ihpv1DjCDz2CQRmqmGB4xuw1tqi7SMxu/crS1R3YA/n6d4cRm+95iLxwmzl7VOXv4QWv46m8cDMjDQSRS4WiAZCfqLmR/98xHFibhC2Vrrqv+D5BtVQbdLSVLPikGlb3WRl47fB85VEHZgJykxDINZpJs=
  template:
    metadata:
      name: forgejo-runner-builder-credentials
      namespace: forgejo-runners
    type: Opaque
