---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-ci-credentials
  namespace: forgejo-runners
spec:
  encryptedData:
    token: AgB/ucR9XhPxaJjnbzrRMazllvyQ9j8ApaEl5HEkiOZ+jNpgI2XDmQMeGG14dS7HCzuOQGtWSQ22kR44wi6xYaD0ovcZhmfjyw82U10E0YckZqhCH+mprJsbPzUhtk0yHRdEvTkmbmZwrTt9rziJrhh+3tA66VRFrL+WifXQCEo9D5/XCP5MTMyo0fPoAFfaWP3SfkbzBeslTAHsgQ+5BJTu4DjHC48fjrrCyCH2nmhEH1TOdsoVFUQU7c88BdaYyY9vHxwcwfuDcrITQdzvcy8a1BSD9uHidVo9TqggSu1UR0fWFO6JPKCWmwIXlPGKnGw8IIhFIitIJVm09qd7TjU3odH5iXCFNfL+iKR5ezQ6orsItbyUl1Rw+iK77t+UDKcqB8wVOh2o4ZLR0hIsMvVenFQUZprDz28Y4ZemVyAvd22NvArfwwRYxXb06P+h4IxZS3ex++mA4H3D3ujBvb7xTTSFR+4gtiLTsjBjiw/vyfd0cmclMW9RBQwbe54SRlHAPesrzaJs1awMg0+QpHVogQ5u4fux0FfQZyzNPweq1tgOAMJK17PPweuQx08Q6tHiWCf+KoVv5HIHhzzrL9qqad6swjuR1OJxoYkXfu2d630fOUgY+Pi4acYWat9srtkGYWljDzX7bm11QaXKNdErozq9mlkhrdjY3yPnWkQQgIteq8BN2HUEwgDFlzvExQKKJnpoKxqcBU06LI6D5+EJeEvMoWWMYaqL7Pmg4K3+qgJG+rqpxsKm
    uuid: AgBlQR7s4O0QCd60W4JjfHaMxMOr3HxxPfKOsUgwfK3lJQQsdsgU/O0xR2IoqIhGTgvlRQB5pm6mDsXqWtyI76OtKGsrTxwsaI9Iatoh647WFXkMEEEJ4DGtDsDYF6qsJehGgqGBSybD6L2HjuUgOysFjD99ePouYa5P/zXfmslvNbKGA5CqRPKtgAfyDeKAhs8DalmRRX4ntXRQD+vBRJXQi0ez/xUo2hh8f+otSwwqcYPASovKuRL1GHrnoctOyOr6tW+3Hc/UAnk1RBjt9EvzZy2c+Cr/3dK+/LNb0D+ZAizX91zJYXiRESx62MHr+9MTVsHyQ1N30GZKCvMw7INWysnR3vQVVdhAi6X7IX2h6kK87gX7RXHgik9KvK629qCk0iDTgY442qyr39ZKdBcrfvRjodMyQfwbC5sT5qxr5jy6r4yY9VPK1otVzxlLSnRX04x/I2EtKwMpPOuHo8IJD4BwxUbEvinb4BAwZgM7llnsMkaYMI4/hPV/aH3T/Vy7DY+uVpmtHf5yqYRsGKgEb8oJ+fipRuVYbbZO78TJNVpXJ3ncR3v9plxSjlzIcps0CPt+GTiXkq4lelt1g2I1fCMuBoE9mqbeAZ254jcCvO6wPVfjDOMLQcnw1+QW5UacmCo078zeE4Nukh9oRww3gREg2OKZl8SI6HxfrgiDCGMTDbjezXsSzlQVsem8TvDjgwDUDxzOUzwFM9Q4VdE6PWcsO+ZaKNormhjRv+hjY5hDoqk=
  template:
    metadata:
      name: forgejo-runner-ci-credentials
      namespace: forgejo-runners
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-builder-credentials
  namespace: forgejo-runners
spec:
  encryptedData:
    token: AgBYkWNC5QHZ9ytqT98BTg6mI9LwbNFaKl2QGE9kmEb2dloVmrQslsZiiM0E12KYfxMN06z872ZfDcs3wlaruWT83HLBK3+wv52hat+/64r0oN79mLxF0K8vzNHXFoLurS3NkYHHcOaMevdLw+j9UqtSJV76Po5h6Ut/MfX1MDdqc0qAZD0wbMaOm8uHEhpdab2RcRMP4FGdCy9RMloiQu11E1OFiKuKxZ4yTZhHctiWb+/RDuDx5Usis+Z8yZFSYngG3eed/VfsGv/T6BApitqn1rx0+PyqhzLhJdw4SGZ3BavqEWpjYoF1EzYR6iH7UKt1aqFlepNnPyVwgki7CHNG5EeyS0CdfhYSp3QHm3Ht9ZMBRLg7+NMM0jZFOT+onUTb7rdnCl34IimmwXvRQgSUC0Yk9uhrhUXWv2xJHHHP1dG9FAX98cmIRCyd+S+iGC0sL2Q0MfHRQ+9S4ytQYwjr9EnDR2VCA9gpi0xk0VWd+J3L9olEqabFzZFSvGzIc+eeyBL1UtN3Vhim0cfDBUSWJ0CPs4J0lF5DZsDjcv59H8RhXXbKYAtY7YA/E56QPZU67EuVZQaE8taSmzyOWKQifm+NcAT7NPpVHbTNOTZFdRCxFORaGF5fw1L9oV4eLIJZNr2CUmdhRrWwUF6LkE2CL/XYXuJ/Pti08TYSlENdKWTaRGwZvpjQU+d7s15uZDDMNP0FiXQGjUkVnaGIvqfbsoOhH9IibtEUOzsZIGg2l1O6k46AcNzR
    uuid: AgCHC1SSj2pW2Fqcqe4fyQRLu3zhCQS+m+GyqaW74f1utsrxfazsbRO4QuvrRckqYWEGrXHFMHxbP1a5WpmkreagOWqqxgYa6QaaBPeEB4cC/8rRvTmJGzaPRdCove20T0fKieMEL5dCXGkUE51jlTAI4Iq31px5uIeh2GJI5gCwt80358xNIpVBPgX76JGOsQikCk4Y80fKY3n2baFGfYoIjmVjWY7Ay61Lgzoic77yR6G2Vsv/X61iLHhFkTeX+D0nvjXcFhYmcmdC9xeywc4yCIxXhuNTkDYtpcZxFUr7xjSHEc1ctv7ibNoI410AYV4uWOP+rpFakAZYyVM9vCsqFdj6huqkBf0jIjwReQxR7UrDtK0mgLUNzT+AzIM2Yul1yckqNbDSkMRRSimKtBgb/51rYJ0eaEyDyGTzfovA/lgh6X7xJKCHAWKLJliGNO7SiPdtUeUImDUizvOgLlQTbibX/vx94MIOZkp5DDpyLbJDoQSXWVJOJSKNhZCTXCoUZOCI+6BN8eHUknRYk1BDAWVHCBuJ3HrTOTokN8HTa3JKeWDtN0OL6UoqeZVXeirwkBw868Sq3xk4Sdg+mCKsRxP5H0kDsRCijItQFkJWVWs750HCrdUdGm6VWPijHfbsQklS97rOkUtpBCioQPqjl46uGLsvRbhRAuehgiehlMSEfdPAUMkNNyA92Qc7X0VmagVZ/S7GcjVkPGKFyH3hX3Z0hEJp6xiNXo/9G1ULbs2zu3s=
  template:
    metadata:
      name: forgejo-runner-builder-credentials
      namespace: forgejo-runners
    type: Opaque
