apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db
  namespace: gitlab
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 5Gi
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
