---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-minio-env
  namespace: gitlab
spec:
  encryptedData:
    config.env: AgBGzGG223pEM13LCwUHlOnQuuQYOf4dRsiTgti13G3AWlBxR8p/GkuPWBM9/Ju8qD0mlWv52Cb6pPe6CV6Gm4Z7d1/lIoYlyGEFKurdmUZZgszsyr18+9JQ9dBSGMtxouE2o/mHhtMwbKkUgT9QBL/IkLznv6uKer1QqHUxBcW7mvKQzZoYV769T4plu9NLFV1eopDCCgo/eCVXvLhO33Prh8qw01/qMEwETYFhyLb+qpt9vR10qaFWRqZbybC+S945ynn19rAoWP5mWCde02e25/s24jGIBlCX+KG2XnwnaF3bc9f2la1DlwtGxTJK2xD3fJvBPYlSqRxbMH3Du4pCQMjPy4o1qBWPbJCjbEiFFKt2Z1KFeBRI+bAVWWVi/h2O6YinQcAwism79fd2hBqYVRuo4jehyF2oMyMwQdDx7S0Ra9F2fNUU71ZzzAfOc5/hDfHRJ/zLPATtjjg+4zCN6anm3nSn5VKETOtxWtkIZYE7ygj54Uh7fniP43FP4XabMDiueRFkvEkk2vSnNrO00crQXpw95yDqZiygMfHadQtzxu5YIBZMTDtBwO7OF1/DoymMOSUjwMvWccs3O84ppJNMS2vsdRHU73XL7vMLE3clfHeuhFhGftWEdKFTGToNQkb5DiS1ignbJAssdxFNlzCsE4/B9zWRzQ2TV/mPzX149jVqJfTz1cqrQNvYxzhnGaFuVJSuQ5SJGpplMiCiY17o6u9hc22kczID9WtpxKDiBrq3HC+oFul22YrK8HUwbqz7+CoHvRzvESD+Adh+1wn+l2ShB2GWj9OLjozqqkI3dYH9rA/jFgctoct50uABMtpDepow6A==
  template:
    metadata:
      name: gitlab-minio-env
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
spec:
  encryptedData:
    password: AgAJa/954s72f4SSTetcFz9FsJMKf4HjfVFoZ1kamX1rMnMFN6dQJgynAacEQ2RdWce0XNz4/PgVIY61YANz9Z8mIYXJMnsHZ6JKOoF8gv6qb6rE4XOXsT65qj46uL/hUxyTLaUFMw1HgKdnIVaLTk7r6CsDAWnTKbSgpUH6FAcTG376Cf1nWsYmvpBDiAORTYr+BT+LKNVQ0M8+5EzIs8gmYpW7HRqgnAI5meO/lND+iVH3r8fW0yqrVLrFFxM+tdbRiUvFV+xBsUKHkIOVbytQFngTHqbMolBim56hqHZuTf6VLXSUr2Myy3VvaFrN4k/jhmYCwv0v8OnF1QafAOX0ZaoV3rzC6U2vsP3TwcztbewvkpUvCPknXZ8z28Pz4hoTQSPMxdfU///0tvZ8K1U/YiFrLJDz1XJSPm4lshSvjKfXisAeyxRQxTmQz/2iXcvGJH1fk1xHg9mxW+Oj9FO3apF4KXrDR9E6gwA9aVjp+hmF3i9hR2R1zRkoxm7ARjs7YmOzUvlRBvlbMzhZehFW4m1DvZgOpClunLCXi3RlNpR7MaDPdcRAl5qDBA9E2MYo28QTpo95EpHhDKEd+2OoJG5KZKtmSzaMat/PDNuVRq+EfQWICiFdTPf8vbqxEf1Ib1678ERssmEsmlXx8Rv3wtXVSs9YzmTKngnqFYQ33bJr6GkSlM97DBQlqEdk+HcAC6gKH1i4NXy/wm/whfKgzwp/aS3fMaoFRUvgezGaerNp4r/et9NHaA+vcw==
  template:
    metadata:
      name: gitlab-redis-secret
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-initial-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgA4GLbF1HXYe+7ojr0OFHQvWBbCz9O/OwJ5n6SOFcHlnPdk4eDgi69EytrxrWZmnQZQH12kcFk5eAIFSJlSHFct6FMvZ5N3YrD6rD8KNuQqGJwpb1BohzrXy6EZs7iKscBhy3uRuoMTjzt7YdmfVET64Cq0qigkNQwt57Kyy/X9Q/uQDpD6wb7oiEeVi0S5N+x9OZQzy7dm7bMlYYr2gH7RIUmOEX023wAJS/61yRAcYFyj70JVcRquekPkrsupMruw1NXhRlljl5M9Dovp5MMKH76HfVhHXgrEnqbg/MSmfVtf7mLbUcWL+m5d+LvazgrS0Jgv6WbJFwZYOs4zxu0Jk0DCdJ+KO9FJyX5UEa/a2D5AP521ieGnoTTj1Dj89YFOP75HLCyuCSnIgrSTn4x+d7zjaS8djmY3QIrD9Rpm6rzOv0P72cLX3JRdnsLOo5gGnd1tH7uJMqqXNS0PFbv+v5nMP5vdtou57haDrQx5xp2vSqk+w52O/1c9XOkLggL5fymb4yNloUwABUKOuQ4ji42ioQZr22QHnMmZCBYc+9AVwiYGfzuiDj/xU1LiB150TB8i5IdtC/Gn/QfV9bm9YZvBUomBvwS6M/9iklD9jDd0Xaq6p/x6Bis2eb/M6oxTBi5cfS9z0PUWuUwqIu0vfZFSAyIp//eWIgaLb0rf42pwB0OR9Hb2+18Q77/I552gtpuzMGxo4Ni6dyH+haXUA+B6iFRUdwRUToQ5EF5tSUjfSE5I0eTGkgOTdw==
  template:
    metadata:
      name: gitlab-initial-root-password
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  encryptedData:
    connection: AgCHOfOZiMN71jOi8w9Ug25yjjWa+Y3LtZaeZZIzp1GE+7Yl3ipKkg1WZLD0X6wKd7ih/ppX47Px2QxB3Q1GUcvoueGsWJUOXk7RhrzG/yURtjDfiS/Dy4aG3xNNcfaDfuIpngXp/wa36GS8VDYJXj7LVnkCrmrIm+LoJGFU30FomQz2hCjeNeqIEl3GO1zuHlzX4xAZ1fDruz+BvpujS4/RmWxQWbqwU0lNUoR+XtEKHCz8TWlOn1Uo7rQKE72VD22SqwcsxbUTPwBo/HmreKnc3VkNJRBn2irCdKaueK7VDX6Yph7Jrg6HkYxjZ8Jh/mOtHjG0mo333p1eJMsENyAu3U5OMLuAxx9AWNhFSqe/uEiio0ZY0H6SMVodgeZTHN9jYSLLHAjg0IWRr3nqXJlvYn6dyxCUQz7dBvC8aTyQOOugS/j9/5p4P7qpgXvJki0qSVZJrNEybB8ee8D/QrQ/TVfDkvH+iZi4Z5ffi594HsD+VHJNNroI7WuaO83W8jQRgAGlJ4J82eXou4ExL5b2+89JVO2quW/8Jf8+0zBqV82doL0H8Zhyxrv8g0GC7RheFh3rD62btNEJbhcIZ/qJtRU6k4DD+WDJnxnZD9sG4n9Od0CsueuYTUrF8qNPVblpWNt5HkAxoU8PjeSk+mCVEtColsLMB91JtdQyqRw7VQQLHxME9tLldjp8lRTOEo+81Y1rss3eHZ/drR2UcN0iaH9tpsTNuTRcic46jjg113JX/vDBTF8fIgOLDxk3dDPx6LkPVLwyhcSpgwqJpX5K/U4lopkNxbV5UQHV97kpH/y97G1P54U4dc3+kaItSG0zL+v63rH/otXdAK79IV17cNOXKNMmYTFl3YgzIjVX9VRVF0iB3FHqZnxWOHc2WFD4uD57AuTCrNk98Uxm6poxhcQcaj4VUEpyW2/xmGm0BRR7Z0drv36YrMRt0aVjKzx3U9PUDqPoCQb94Cmt2T0pc8JhLNcv6r0=
  template:
    metadata:
      name: gitlab-object-storage
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgDIT8cCYYb2g2sbDkBKV1v19fYXcmm1svBchONpcnzVDb5qLKTxK8aARpnYNTNomLeMSZ54a9rVGa/WLZ8Pd3pbB78B3QjwlhTR/B1uXXxQX84DZJPoBuAtJwqCVxMw/CZvHfC2lae+MabC9O+XZRz89NDaRnJxk/uwnp07rh1/ML7rnXkz7LhzOf6LcBUnkn6SzoaecJp1YvJUbgk3iQxOr+3DmAyrP4ivRLcfVF1WIcGu6kJvq/IHXmrtSx8ihJtSOEklfVwcJ+JbmRiQxZWuFB+iYKPCBeDy6ysnTJArlvSwff1pjRyqNLmiB5VikuhJ/0fRy36S/2W/Ijh2slg0UILniIcwRtwUnKbJ5RvQDh/8mYU4LeR9lisaBguRN3xvKp5Xc0baZDpYnCsEvfASWwAtwnpq0OgYFJx4kxgWdrPnFDmWbuVluDO+hymXeBnRwcblQ2I3Zp8QYFXObkFQwRW5JYmEWpbj3CtpG/49bCo3mp4AmjsKM4fZGKndFywRt81ONlDKOzCoO22EoE4N/U2RW4vKmayKXBm20whPXxmvpNKkZheIvJP7YsA9UWwDnp1ibDzUB5m0DNJ+jujJs9zob+eRA4K+KHXx5ojUiMVu+sgW/WAZ5Kcat9MruHbxWJfrKWEJhBtK7XahhN96jB9Z75tga6ffpJm6OYTBaf5TqbHUHiCplWNnedyP6eZ1Q4nE5UqrwY3ZfPimahHrrJ3j+5IRRVPsRl1cmQqD3FAOeKIht4X3GZlOrPU5qWQq7yunV1OAuyujmfABYnJq1Xj80Xki1JgiMyi9PTygrtL9iM/cfQe4AXSmj1q8BrM6RMhHpwSc3ihK6g1Ahlcg8QocinPYzzkMoFi9niWl6P48wYknxt5THzjy8cu4/A4BtCCXg0VzWxCkJVe7ujxf7ZpOp819g8bRRpqe9DICqFimZKM2IgBk3obGpwOyhRHppoqlcM1pGe4EG4HlnY3x8Ms0/Omwmx9j
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-backup-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgCQ8Xdw8EoYA8SwuugKXHCp+VlpG/6Ky75KAkgXbvP2sTSEvBTeMd9HUTyEkd3TZU6+yQAImas0UbNfCFjVJh2ZbgLSCMLqf7c1DXchSHEvCjFsWD6yatbphdELFJJYjJXuCeZ2gtRxMjmK4Zj2+miRruClHyWrMgF6ll7up1TcrTt6x5X99MIV5gQdaPtwy4hudTNWbAM7o7P0G8cbrZVJGKbI95yg3QeISY2Fz0Wt6J3S+cezNVvEWQNnSIdc4cYn4EwOw+ZO66ciI7ctVqMPip7pVTUadpGgOeXTI5eja/mgOC+rdnBHZb5WIxc9Anaa/l7lbICxv8ds1z9XE5+i3/sc9HtfH3g1vdQtVXJX7QoZ3+msJXncJbGUZIxsGzjnOCiLGxwnsmWPifQSxKwKmTmoY0N6tzJj2NeDo41TOmfuKrlxEE3XYxB8C6XZfNCwcQvzcanuAhUzwh4vKU7/MFFLKOvzTb655Vlg3RNz1/vSBsJLs5tV1RIAnCmD7moPcTjPlC8ZTlTFXO9HqpJXRpU3fu+7s+GmhGYvOgbyLWTYJD11DEhfQkAPLp2Hqc5h4uu/Tr9KyY8WBLcXXzUJu3qQKwEX0wwosnTuGNnoBwjUu5BLrDdbzVjEfBk7B6IcCsn4C1jYz/fvClEw5HDTvAAeadtVKOeikTzhy6zRQMSmbNGUq6IlSxXIoTeHC7umpVl1FQYQHAXKN1E7T6okj57oVnI+USYYG7lrz10i/KN2401H61e98O4VnyNQIiv1Gzzir5q5pN8BONTev/2QHeX3GfYxsOvGEaK1MgeW5X6Vuxr//ZdASdW8aMDOMBUdCH7bzUs/Chh6tkxxhb85RYo9Nkz3mhnF68U2Fquhsk50ZAZuqE/lpdFvgLuIF9m/JBLtSY3/tu+SRDDWqWtGFVhd9P5SWjvtsa8HRim+IFQh5vqJB6RN5eUdS34zdPr4TOSV6Eaf6HwuC7KM38tKNyP6s5kDmg47/Lqzg87xwDiIqPVN0byA42gcQLlr7iLxtQEULMoFTzUYJA==
  template:
    metadata:
      name: gitlab-backup-storage
      namespace: gitlab
    type: Opaque
