---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-minio-env
  namespace: gitlab
spec:
  encryptedData:
    config.env: AgAzKy5SIBGh9a4XufEa8z1RM1SViD9MC6QPv4Ef6/pDCVtD8Q34bCh5DJ558BEJbLDpdnfHef+6yCHzhvrIHfufg/vnqU8CfdwaLhDbtqOM+gnw6bKhY7u3yGEoFuUqdPOVQJf93f7bPl4OpBXEMHj/do/9/6520RaIQMG6JkiXxTDIzjBmIwMGqA00WvAL+z60I3DMF0qeFRjnSBaqkf1vAfxwVX+Y2hpp/ZdoaypeelHr20zJAzd9tMAbK5jY0bMCrsijLjYOiYMxZYbxajkTJxq3WGdJ2ewzv4LgyiGjvbIMNm1a6zfRCEFzDyzObDQ1vGUJIAXPJ8MoJ4OLDbGYa38EQtouLZg4QXu60XI64kxKHXQ32g0Myfky/NDC6/Kk+ySVerpETza+Z9X/6nOKDZGNQCa9lVJSKMEQCKpPh2FfGRoxhpHWcFSbELUpOhaythKjUdnUDJovAvVwk+wQWS7FkioiNg33UFRUGClszMBjuCoWQjE45M9+/M8imZqy3eXPAOOD657N3ZZzEdgH8HqyiQUUd6WUhgqraQBGBFMCeXnNBNcSo5O3N2kIBFgJNIzHZYgDcBKNJJ31ismbeKwt3eUAqnIjkE8hMgcOs+a84eAOlNn/CypRTMIlWys8uUxCl1YGrKQcaYscuynWrCosk3snod5p5k2TfJdH5VU4mftlrpKrJm8M8421xP13XZIpYuDkTnfO4OGfbvxZAllfGO7/h2XQgbpSeKH/ozquDuOxzdaZNXXKhsNQt409rmEPT+ol1U9+rsenjlewKbwV/QZ5gbqhRxIGigM3PnTeQip39ubgwX2mCXuK6phIOH13/VG5zg==
  template:
    metadata:
      name: gitlab-minio-env
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
spec:
  encryptedData:
    password: AgCOGzUcBikN48H9mzX0th15cAwOGOmQdXHBjXGuTJReTKu8DHB20jlTarJqbzzDvjandu49KyTf2cbYwQYqubScF7I6KLFAOppPy48hYvQxkkxDZOD3A0DR3pAc2/Bdb7fUbxr/dlDkZ8j8qVOCZ6dnO91q8vEQMcYhU1NC3lSuQh8klNhV+pGE/VKOji42ZXx27D0qvZTrKBpVb+ZskFEmE84rvxXNCBh0z9o1fIx7Ip2nhCoAhGpuS4JDIamIara3dZaBZ2O7Z4ArKVkV5+t/Kb7SQM+zxGBcEY8ZGpflE0wGt1twHK8+BBMM0jvExYjzqlFM/QTq6h45rAGVOKl0xnPnoqqGvdnEJ78paQ2AxsTqiC3jSvHlMwtV68KaiO3dMNicb8g8/HP2vZWzEEdq3nb3D7XLCh7eUmgJTmQ2cJajVRofFyiWik9zWAqOHFaE3O6egh+qY3lfhedIrVwuEB4FMKDGK8upSV+SM/bSGvlS0EvBVjzJiGpbYZlCOMZD7dElDk8vWeR1pslwN2KUW3cfwja7w/b3/vjvKh1hzl6UkHkB3rBrND5pzBBpu4/In3WrUaENlH7uT39zv5QFT4MuM1SopkjWTex7Rk6zm5Q//zCqRAPOtiLTjUkGN9T568zNb5GBI8GpaJQPAth9CSkuxfyW2K1NsZbgYaVZWZenPbWQvzFBeVpQ2ew0eyrilvdN2xELx4fV38rHQ9htUrJ6TlG78D7fU46IWnxUnEj8E5HBwMse6GY3mg==
  template:
    metadata:
      name: gitlab-redis-secret
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgBswr80xTiERCuf9maWMifr+rggHWYcs4bMoAZqKKl/Bc1+OH/mFhK9gttaPFFWfdvdFe77oSx/vHKoDvlpHKaNUONyhZUWcqQjlUN3gUS2rRr6ya53o0s3uwrhdSdIzB4lOALXPK+1kW3rve5fk//Tqi6TZPIXPGSVCs5tMXvcoITFJkC51jcPR7ltFmzxfy5xzlxJfyO9+niCdEilpRVkTHxzUJ3d43w8shp4sY7HGRsCR03yhww4TfEINwlB2LhmuAtD7wsSyeJnqyX6InI8afMM4HouuWD1Np/ziOuMlSvOCoon45jsz7P5qN0y5xkghVBFUEne3q9dxXKPq+wj+WMXqrDjfnRmPFlH8wUY6K0FiFNPjJqiqcD5IsnvpPiN0bdftlt2EI6KnfK/3oeaVNYp10jH9IofYHkGEnU5X0O8B0Zkg8UREGLx4n4cu4MhUXIsOesIpzAFW1E8FHq5y9SpdmAlopODE9VuA7Owz638umfUQqYLMcce32TdrAfYTRhqaNJbz0uZ+XydJ+PVCWfw52JGXLwJm0dk+pRaC3h+FdAxiUzw510pXWAI8/fDBicLLO4pJBA+r6fo0vfIkmrq9GRdPA9iuuLYgceUeGn9v9Z1nlCWjkMXiwAR1cxm+qr1OpZUY32RIVQI90kch5NZSrnk8GES5UvBjyuP5bOcs3iNwuXCP4Lj/oeFn0ya4BnH6PE8juVIdYXVQNBeVS4OCgNSV6vJHPKUXXj1WXJfDk9NbNiQBtomrA==
  template:
    metadata:
      name: gitlab-root-password
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  encryptedData:
    connection: AgANELrex4uMww5S+RQlb57rFDxW7i/RPQgqDDTAS9uqIlEjDHFilxMEcTclceJMgrsHNghJfawmLWyNAhRvbvvkWfd5um7S/ZWyYrdzRfoQUhUtH1uAoSGKA1cHCVylt/Ew/FX+oiRssW1ibpplFEyuuDK0Le7ZYbgCFoGuv6X0PyvENjyWdR7JcERTmxlYBkf+9TnArGPrjUIvcFMkVKNY9mgCxCIH8NubBxL4k8RcP807d6S/zfVG2AnNgIdBVTq/WX+l5ksCMs7PfwbvWfSB5Bv71yYdNiKKYL0n2i/VPdcmPct/J2vvVSbQrXJVRJRkSDROFeVH6iMs+XwQPFeN2tpe754jC8VXiTbHJIOIuCJICU3xBB0uw/4RRCDQZWzutJXvUI3sFeUllfHXJ0GGtRINVPJkDb4a0KcrGTQ80m0cp1j7wDDtY9vq428FQ7d1xiEFwXx3iWnW5PSpDYiYm19WQL4ijlGG3Pprygcu60bVy57vGSeOO8lCSDUG2Euyc4Mp82DgEnl9L+RUwh1ZfqR0ylIhDjRmBTTGIu/X/60zy7hKjDTNdSCl/MxaZk2eTJ6GzrYzdFUo9PhE1ga4TP/wYnh3VH7XhFAUL8XHoeMnlprR+J7zcz4USu225eIAm5uBlhFcZnQiH2dQm2lkDkeMMuxF5oOkCKlmBu9ns4Ly79tQPyKb0tbvHkLxPbZ8Bb/00cUAWhZHqL7X2/ILxqGeyeb+kILm+kJmPPCi0puiPUVQcCFRUwqgkCKlbq1YmZyh0Qco17ThBcRoIQsyq151MdyT2Koy6fLn0kZTG88KrBuaqf2+1Ci/dBgmMq6y+vFzfNanVLkyOV6sj1YJ23dMk+9DYAooEPAsdBmw1lxQgT5vwgYgWn1fF8aTzBUAIJERi5RRpZUtLNUHXqu4uZTIUQAWZrj5LYZRf40HCy6lklDrUdaCOOCJ3KcysbFmdILY1dngxYytTaG+cAhaPOhafASQK0E=
  template:
    metadata:
      name: gitlab-object-storage
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgAMhjg3O56iM6BsIrNKEfXDJqqdflZoGmxBgWk1IpqfCTQZT2mdLS8chfVFQ1IIiGAOXZHHHsYMUha0Pv4HLJWSJFI8cbAV01iPqR0dCyYpyIA12a99o3CLz5m08lYl5Gn9q6RWYJhGQfFt9yY9eD/OD3DsUVLSVae1TDFiUKJlAdTrooKsoGYgianV09DpeLQ2ImwGvcVF0AhY8ApPv0cXGJJJRZ1ToyGiDCpSY9vo4ei9WLUld6EhyIJIT5vR8XvAanS3Ld5QADCWXgQcghOtlPnrVUC1/pC3/aVBvugnFuKiROZ5S12wTGcwp89t73kUK6f0fm4hirt6clM1P57jBGK/lO3wmm8TVrZo332Y0WbDp6IoO9WJinQPkT5xfiI0nunq69IdAIBeSOnhSjee4gOxKVn5esQv3kQS+X+s77Ur1FaJATwO6clytjaLjTatVZiIulPCwy9jUxxsHf9+3HgRJKrYt60ZH40CSRVEfbk/r1eI8s79L5smOoms4fZ5pMFizLd8dRg8p3iz/d/UZ/dbxwtAmtzY04D5MIJeelVzosDKnjxj9J/xz7CMobuxATTda786ztBriumuSFoky81hGUSuwjTTX7eyRaHI1+sCOkUDcwu4cd7p9w2t9Y8oPj8f+7J44v98Mg53DUiHlsuB+vLYzQCB5jBL9jR9OiQ8hkDGqDaKSJrgxQ87oR8rzKmqXrf3c/C9wj+sxW4vIzeAPe7ZDctK4gMRRylVVEvwcTD0NwCiLUjF9dxhDuV9cf6PIHLhzSEMMM/zVx9IogJsvPwIOqYkjI7SYkiTlxqgQLGriIKajxB10bdwtwZjcIobtNE95a5rme4KQ3ZQceuqeYF6kDVs/99U1VQVGel3iYnYsNosjsdIQExzFt4jB5dhL3nvhfE1E1GDU0jkdsTJSeaPfI4YwzccGDzhcA0Gds2pDs07YSnD3JiFDYeXU985/OC5qofVIgYh3Wat+4McsCtNtvEG
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-backup-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgCgIVWb8QlRXQA7MhEEkijK93XQJLocWsEGmQvwPfZR996YH+PV+/XHp/HvyBa4XLL6WJxkAgKvkWCwUgKfgZmqj5Sb6g3OcWmIEx2tWH3XlmSONxAJw+NUN5hw65ROK5hX3zNHqL7yf3ckoSxTjoCEuCsLq3lxN4i0Tt0P4EC6KtFgyZECb1MHk8u1sj+KKFD/WQ5Qr4otUuxifsVw/p/kJxo8kUJZ4sSJHx0LNFRFxsoiAAx8exXXG1tun+0ax5r5w6VQRghtWz235B70WQmIctPAhdl6Ghxxf1X0ieGZh116Wsbtv0Q5/3OG/ZdiOqnwGH8JtzGSNuWSJ3R2nfVc+9iA1lhwoUJ8itZJ/GGzkhAVAr8cFoqlvDZa8bqVnizqPdaX73dVXOf+POKS8Gndeex8cZZSfV+vvittmfKTCJpF1Hzv8qqy5QVFdRlJCb9RpjAL0cPyfAulYiLSFH3WzjSzz28A3dm1YxddKwzc6Zny7/ekW+ktCLK0wvcs66b9a2hO09sOq3gpYU8RYuQam7zK4uAf7tXsLIE4Q96nf/C+RkIh+ySAMCNBwPdT/ssTOng8iW5HSP398+98ly7A4vJ024GasAJhTSJ/QKk72HkJFTjM+mAWM++TxhrGMABUVp/RevGaQECOR2NOdrUNINPZ146zcz2L7oo65N6L1tPWQYIXL6WoPg8MQBm1QfagxJUHCzgrLATvB956LRm1rXdHjbcl3MwK4lTh5h3gSsjvqFNSdlZ3KRsfSFicIxcjRglFT3E418jjbYsBVVd3SUa3tYmRPbWS9b2ceR1SdShJ7uKowOkB7OgA+D1GM24lHEZcyY4fC0LWHIuJj6z+Ngy4Co0UGMcXIDPF9YlAbsh4+NuK9/9mJfIDiHQCW0VIVf8WqkGOM0PKYuk8FlHreXQdstOV+mir4p2UNKkvDFTZQ2vw+NALnNt+k4fLaOWhuqtSOLDY+1ilDbGJ7qj4de0sCrS7YSOp1c+o27zXOATxNB4wVKhhFNbFhZYoCOsFvhHxMVCPxgQ9Gg==
  template:
    metadata:
      name: gitlab-backup-storage
      namespace: gitlab
    type: Opaque
