---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-minio-env
  namespace: gitlab
spec:
  encryptedData:
    config.env: AgDI6rq/GEmAfK+Xjg1uxlWMiFvemPcoifFsCk1mN1TpfLpzGQsU8UzhM1dhjb11HmjYt//hL/qe2IJLxJgwwjuzc3huPUifozXP4q/17VF9ZmWRMaZCdT7JmGGRgnuxQFj1H7XS5lFXnh8VSgMc59KwZXdE156cDb3TXMBBzRwI8NI0SdytmWhHhpgkx3cc97uM4wUv2mtEDt99yNvcTGqyRXeDKearWuiyFesRHBX+3gFLFo+CjClENKkAF9dCdygy1VPfpyL4vR+qEHdQXGry3uWpUZXKwBwERXVqQA+nVRxKr7TswUad0HM7A48RdVOodvNNsyw56y5/et8uG0VPQ6Z8V75PP0R09gflWQGVco0kccVX56cU6/6RaHUpqARNC2KQtraPily26YjK6nythWgIAXKU9/HBWdbtjXwiHfVhyjlOleEUxW261sWhtSKvKw11p41TWE5tJfwWaiBfdY6DHQhBurNqOkI7x47pMSwdn8iiyMPcM0SQ/ymFTMPp/PJwR26VZ86D22Kyv4IazeFuNDstXtaHgoSBdoIbmQpQNR6QqbCu2d6Udf7hTT5bhJdvS964Byz0PFugLwMxwqv7GRoaHPcMJe/n+9cOvdtknN1VlnNoNvxKZQD3eIGpN3kvLoFg6G0i0ov7DYf4Er2TXirNbLiDoKdTfSlwCuxRVgFhBiI2bi/amlPuD3LdFeoE90dIEr+bESbSbWshzh5ernAidiFiZnzOOEThYT4qt/1fUYoBBfI9kqjx9Xh7G2MMWlk97VqzzG7xaRJneeM9LCtoZBXYFwksfoo2aOdPBM9lKh28fG9BjhYVVpsZkjp4PMcrfQ==
  template:
    metadata:
      name: gitlab-minio-env
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
spec:
  encryptedData:
    password: AgBmfgrzPalREtMhKVzDpqcmkO43errOBWTJcrbfC1C1ZPcZzjwGyyNHiNOH08aPxQF36qm30A87dPL/AcO7qyz6i9kTnkKY4K1JHwpXA3TpSnGQq6aWNC17+Mf63nGuRUMuFO17DL2JLmllRUVHbKN613oO2Em9cD+Gmods2vfBbTc85PnZNp0XA205lf+ndm07urhu7+6fmYc28hJoe6Wn5buPoX5R0kWYliC8mA502zaIykDAhH/xQ/YPDC2P5EkWdAFIzozdl1DEaI1rrb+Tu2NgqhU1Bbkrmwt7R73JL6jwNK2oh9madbwcTiZYsrsm6lVDTmA7TQj34GNcTf5n3KdC08jrJMdimCm6TEnbn5ujcMRZNFmcOY6f+NhTjZy+VkS/9JrM83kLvpbR8ftztacdIUiah9hJ8/XbLjyCb20IsuxQmzrumZV0XkXFcO5vNzcEutq221sOUzjlW9NPXQyTEf84h0JFk5/IhBIwIQ7FXoFO4nTwTQdmXBvG+z2lDk/JABxuPE4Ebs0QEeWrifuBoKeBtto8mMKAVnlDK21uft/lRIrgzyHUVUrfQMkfFfvQVeGNPodoSpVZAiW3pE87efvez0Bph5ZjUdEzC3Lqa9hTpVrfJJZM8gUhTWDdB729vtmsA8rbERDy3PtOBHWgqujR35CdsWtc5kHzFPtIlunhwQ0+6240Bv58Vud8cou7ZIrhqaKTVdbtRHhejk6HR0wwAHlGui66MhxOCPHqMNeJmpUzMIxybg==
  template:
    metadata:
      name: gitlab-redis-secret
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  encryptedData:
    connection: AgDGdwirbbU4qP/fTtsQFm/zKloSEcMmnLw8uC8o+AjZz+1sDVl9J1h1mJbVZrQCVH3RArJsr6fxcF6+geiQmBu0v7BYGrhhr4DFs02TTpIK5Z3Xc+91n7jJK+JYEAWhXVwZWs4cbc3tQ0ZsurPtY3eF86CMB/bvGys5CZ4b8udbsPdz4TWi+8arB1e0DBkt241XepwHzK4xIWK+l9kYb0ZovwZ1ZetPOnoMw/TeqMRAf14sqIVb153dGN8cz4Z1UKLD7IDoNS0MnpyRoqSc6OWEczHqtTAiVTQ84weuh5nHBchXLcOUlZWhvmLaRM15JZCa1Ichp2ZGp5NDNrwWktsScqovzdz1PdK3qT3f06chCjmb5PpY3gHWNVDZveVNPTjUCzsYHnuve5J8OU2fGKQzKJlqNmCXkpdFU+r+Q3XGBXERC3ifGrtk8smQHxs0TyzpFWWJgOGNyPrKNAXnQZvxE1bw0cSVQh5x51nqKVaJ4dChyOLnalxrPXKo/+OgItS6qkVZn45hwezxU7yXqvsHDTr3Vypf6trt5w54SflilHKckuPW9Yyf1AVXnlJjTEh33A5KW5j1JRP2cq3Ihff/Kyvkm3dlY5ILGyyPHBTjLidwfnQxJoEKOLkf4ot7bRSUA8rGQ7/cR+It2EQwtcoRSErUu2Nf8F6m76tfLNCpcBQqqfnP+T9pRFN2myIU02VL+Rm4dCKQLIT+ZX25PcCpmiLgK/kG+Z106162NUiIR6W9/mSHBJ1hI5JfAZ9C/WwYm1An+2Gn6FKPpMRA8oIzxmJpfaMO0UBk1STaStIHU7jAjexCT5aVhnY9VKnM3YOZp5YrojPL0mxoCqb4REtWfJ59mmmkytUEXPntXCKryOc3HYnzFRIjbuwvnZTczqz5K5x37w/AifIXaJdWjTnymDhzpER4jIHY/VRDOXp6pRvjBEhYX3ycrZBQdEQ0Xe25GZt/Z2aQ08ClFM/GjyuCmGcLESr1ukM=
  template:
    metadata:
      name: gitlab-object-storage
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgArVc7u1y0JTB4FvjBGNTAgUBLGZOQIwZFBrGgdPrM2vqkcZt9nGJPvlQ9Lq380IJTpmDB+mAVkH91G7jjRy3US/cgTWNKYO168MiXjbOeh6EUsEBZhT2foJ/5aNhcfv3n05Xc3LY3iix30RMOKCqSpzFJfAL9LqRnfRgm2fdl0xl68As4ebnNCo1wbTW68v7paLfvbjFPEcriMVA8AMg2a3l5kSBGAeyzv6DWPNMNAmL4/sJvPOPMkQ13Xz4SHNi6jU2WOj/lKOwi5D1+E6CwiHRZ6JpSXXPQq/tn5s3Tru/Bx2gGURD+JJpMRejDOiS6+2uxElDVSDUQI/JnIUQhrlEOu9WksdL+yKVWCBiUuedxvM6vWIUke9rs08yvCoYqFsd7jbm/9wv/j+ZvV1NOjueCKnYbNXjgy4o0EvSr15epO/ZLoRyMv8HkfIv2PkYkBHjdCmbdIJVPEdTrA1gk4biZ7d1txKEii3LYoaT7ka6yAGTwNH4gB/Wm5GIvoy9izHcyEfkK0VyYrbja2VBjJBZ8jq9ecqUtUkf8cZb0gcMV8JbsjCvjzSmrUIsMJpQsapQGQmaUqfxM+AjHeAb7qbJZSIylT+fLyIn/0yN+p2vXEWfVKk3qHpHYgnMB8lh+2DBf1aIuDKeYXh347ydfe53szJDaqm+sR30O+yRSQUCLh417puGloUiVArMF1WV7W1bQPMBEwIREd+GfK2unzCgVw/5bkrJ5jiTMeIaQgmqzySrdOoo9Aw9MUSpsf0AGirvqxxhZxSqueK3Lg+BdOlxYQi7TbYbQcJA/NeBnMuIm0WNZ4w8mlksEJZCYbF+oYJSVaGbKdfrkXW9G++AFHoPPoWZ7xdJjXIII3W3zcdhTThz77ymuh6jD5mP7upr9Tl3zgVWPBU3S4+RhH0ZlsdQ+UdTvw51IGNnngrBAoOQru2V4Qk9usfUtTKRNbzv7ffS3Vbv0zE1AkgiKkRWRuR2z/qK/Ge9k3
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-backup-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgB5pbm9q5XfNFXBSCaOg2XkJV6E47aw+BCdXDsLX9r6tzPUyvFonOjafpHj6XSwNmFRac1in1Sp/O9xaWNprbqwCAlPh/iBdUrAW9DosVypWuAmfkKRbumlDG2g6iv4BYXW9ePwx6sXRcxx6t+DVI0vmRQAwAjonrqHb5FvElvXUElQB2bLRthSTYttoC7pnqx/kgLyYfrxZSWdq8DVM/P2SrAhNydDic6fjiXCCjA2g2JNSWr/0wkxQ3OBg4beP+eYimoo5szcpU7OzM1eKc6na7PKYBPc8CEgnDSkSx9ZO/97I6CUk8Nv+FL6bIQm3y4aS2HGuP67ShghI59wukR1iEJTrmG9DYWMqd2t2iB7G5HgLtktCAeClYenEX6V4WI6vLCw6ZkpCbNQ6GmX90A4gnzHbnIxee53VONkUGF1UAL53bBdI2YCf+m8ixdA495GQq3F/Zq1jsnWr+fNKcDVspEMMghNiAVyUttC0OLthGrD8eLc78Mgw5EueIPp/dD4Ck6Wr//9bYQt0AgjjnRQ+/HcgglFtPOgB0qN+Ffq+A/WiSLj/lX+EqxWs6uwiv8qyFDYly+yI+ryv9NktXNxRQifasf7H7t+GkPY9boEPpwckjWD5jOV70rmoaS4I2eZWmEHrdp+JLzHUdsihVWnmZnClJTlE8JdfDWXG1R0q3yU9tSM3s8t5IWAmox4Lb/LixslwJhy5fV80TfFLz5DK8bVQPqwxVuwyMmgd4N1GkyVNxyNHRP09EOLRThYGudPukOdDtioWMg0ji0eyveadlp6hgMw7UVmoSvIbjTPtYEAaeyXY/e8xTckTUlriCSXBfWkpL/nLOn1If8Z7cKp0ZAwfazdIjWkaTkThF3VB4B89HVxVLQqwOtRMP0zvxbw/81MKSdLSb1MLwofE66IrOmmlsMw6i2LosvtvFlplBQ1kBfIM6l9VnSESkRnt+CzXmKfadojkfdq+BWRKTWcMPrglpRQLpnlfvT6R5cDKqVC7UObicbuQD7o4MKdYKMp1vdiDJYx98FtuA==
  template:
    metadata:
      name: gitlab-backup-storage
      namespace: gitlab
    type: Opaque
