apiVersion: v2
name: csi-driver-nfs-deployment
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # https://artifacthub.io/packages/helm/csi-driver-nfs/csi-driver-nfs
  - name: csi-driver-nfs
    version: 4.13.2
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
