apiVersion: v2
name: gitlab-deployment
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # https://artifacthub.io/packages/helm/gitlab/gitlab
  - name: gitlab
    version: 9.11.3
    repository: https://charts.gitlab.io/
