apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projects
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:rciliberto/lab-gitops.git
    - https://code2.ciliber.to/api/packages/*/helm
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
