---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-unifi-secret
  namespace: external-dns
spec:
  encryptedData:
    password: AgAIIw8KdrmCv0o5WIOq58mkvwmbZnUI3S+8b2wqIyHd++2Rn+wcKUG7VOn3xC7R+g7gHqL7PrZ1vpS/GkmtXCMDuKJhYIAcLJtfIpnJA3dzPWvFuYou3PpHH5MR82G6YzppUjjISG5Hc02t+AVgvLCb9KMctvBuPtzsYvEsGMdPEbHfFgrX8BTO8/hlApoBdp3wvbDsv9QIHSX2ip2n0newqWqg+ZAHQmtmTqxflqj+lWGjz/FULdYM2OAO82clnfnSnU0vjoIjBYdo34gClNY+xis/3bDL4K59j/u5REUQkfwr+oQv81GbxJXINiuHUKtyY8NEyd1Frq4vkrZrhCFbkcjBWnDuWh2Re9gxi5vQCdji6+ljPR4TjKSOS+pvcW7CkUXkhD3K51s+Z60CrmcJWoJ1MlxFYrm7t22Lm0KA7zjd12qnlDkd5Gtnxr/PyaY8ENWfyceCqXKSFFnNtepz/7/cqchiM8ZJBqICf0ysbpj/wE6+HZbNq8lTdAs6QPn34091YXL7v4jLovSjbVgIVqKbqt6CqhZUNFixNAdEL5eMtUbXpyvxxbwQKxYWPFsqdycjpIzTt+iAoI7sIGHuN/BX/WXgKk4AT334VU6Yon2PIqZHhQ7HPTwOqh1rEOHS65ibAckC3tDmAmHqPW2jwQACwwuKACENX/uZ6a0wHScB7UPEJ6bO/0rlBev1zaegpUF/0CJS8bbV3YZfJO9GFLDSuQ==
    username: AgCQH2WdLIgALPlXTcThwCO+B7gJtfQ42Q2DIBQRwAcw1L9Dcm+nAz3LsojvEZk0cie8fqaHDmvn3NCWy8r4foRhBpfQNhxxPJf/+GNDBASlB1X8ULlJtPC/snS2x+g5esKCnEXikomTzQ1MZUucBj0lyJtSNhFRNihSD1HtSrnKGgCpunoND/54nLcvnb09wv7MPU6zQz+mmCcASLLcpJR6rdijGt2Rx+g223T1noTiVyVDbpfOJEwdOlnxp4bPcXKwrBFryxfYGW4KSxq3TsCbMuuOinjdSZhiWkIMDI5kFvUz814HtKqVweKqlGc3qtlEU12zMDjkruzwV0uKUOYwEuwx7AYOfJQYW0cZZGXfUUWUYXfJSujl7LApKvqrpHC5aR3IfGEFpnRbSoVVrmODeU2DLgfFxLVhqTYuoS2tzcYnt+eDLi543KU0gNn7IGgXfgsLwDWXvwi6+edCMBlzyx3dEOVabV6FB+9Jvcat2uTX3IIM+9p1522A1RJIzzMrp4UgNztCg2EEOMmOkD+14cGtwXGFYigenEOT8SQERjUaNM5/orkr8fKZ0HQwZXqEJRq47/22tUMU2HmTVa5bvjJoPLVrRCNF1Of1MDo6oNmRYOopQx6KSjKUdHz8GgiK4ULx/8Jv3nGxhLv9vWPiaqHy15PjYqg1PBz5nP482TA4t6eDPLzhU5cKRG1JxvlEXIXSDziy9crCp3MyOFKW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: external-dns
      name: external-dns-unifi-secret
      namespace: external-dns
