apiVersion: v2
name: cnpg-deployment
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
  - name: cloudnative-pg
    version: 0.28.2
    repository: https://cloudnative-pg.github.io/charts
