---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgBxhmmZ9AACSTe6IlCwTa27+Qkeg9B5KE2+vZFerPvwSVUSyUT0o9lh5j+jUUczoJW/14iteM9zu3Qp56NxmBsDMwnB31RI2k2pAxfvnwytbwR1q00InbBu49eOL9MMDjVZcQ/1TttBvj5cQvIjtlWhcCxHDO//nf118cXGEnhyu4mVrBIKEPKvtiyePB+EvI5TXFTwCJdKO5n2WLISUZx1nsRgNmhOqTdsUIqym1na+3ayHahdd8wweerVf3j/OKg8Zx1dDHDrPmCS+wzVBah5q18h7eG0N70tjAF8VZngLjKPxU4gscBWL1lTYmv+NuV3JsKaB/xGrObjysVYbwZ+i5AXDhsSfPqr/8ZvB+jU4bxPLyegcSFfLzY1pjqeS1ppQCKbNwU6ylcT37G5zDQ1FnCLj9IzD71TB03N7TiFf0sCZutNTQpHTFD9DAT1RndDykrm4KGoXglfTjznn+gxpEI/285MKV+L9BOzgTqeZPsxPIoEObyjmLfQpJaeeILJdJIbKIjrMcwxqEBgOF/Xu0kjnPEj8JixgpgnSvLCcemkNFgBjBuxSkYbQ9FNNRNgG2NiwKz0HQyuIdZeJU755bQ3Ic1E3T7WOmVQ/SInlbtfOACeh3NdVtpnkSgFJ4nhjQv/64rVOY6BiA6YAoJhFeUz7aX3LNvSdp9puN20xd6jYGvY6DT0o3yjDZTeeqBtCIVTizXNbB3iixqymssxxn7TFIQnYNb0EADSLWtHkwka/h5QpnAbA59LHlQabOgr7oDbuY7nPg1nf5r6tRvQtLDEOataisfJJXUEADwXE0H7ooKODISbuR/8IREN6ChR4mNZKVD6bdNMiz/CZCem+xC81Zr3
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
