apiVersion: v2
name: launch-onedev-deployment
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # https://code.onedev.io/onedev/~packages?query=%22Type%22+is+%22Helm%22
  - name: onedev
    version: 14.1.9
    repository: https://code.onedev.io/onedev/~helm