apiVersion: v2
name: argocd-deployment
version: 1.0.0
appVersion: "v1.0.0"

dependencies:
  # https://artifacthub.io/packages/helm/argo-cd-oci/argo-cd
  - name: argo-cd
    version: 9.5.14
    repository: https://argoproj.github.io/argo-helm