apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: launch-forgejo-db
  namespace: launch-forgejo
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 5Gi
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      encoding: UTF8
      localeCollate: en_US.UTF-8
      localeCType: en_US.UTF-8
  postgresql:
    pg_hba:
      - host all all all scram-sha-256
