apiVersion: v2
name: actual-budget-deployment
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # https://artifacthub.io/packages/helm/community-charts/actualbudget
  - name: actualbudget
    version: 1.8.6
    repository: https://community-charts.github.io/helm-charts
