longhorn:
  preUpgradeChecker:
    jobEnabled: false
  defaultSettings:
    defaultDataPath: /var/lib/longhorn
    defaultReplicaCount: 3
    guaranteedInstanceManagerCPU: 0
    storageOverProvisioningPercentage: 200
    backupTarget: ""
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 3
