router bgp 64501
 bgp router-id 10.20.20.1
 !
 neighbor K8S-METALLB peer-group
 neighbor K8S-METALLB remote-as 64500
 neighbor K8S-METALLB description Kubernetes MetalLB
 !
 neighbor 10.20.20.3 peer-group K8S-METALLB
 neighbor 10.20.20.4 peer-group K8S-METALLB
 neighbor 10.20.20.5 peer-group K8S-METALLB
 neighbor 10.20.20.6 peer-group K8S-METALLB
 neighbor 10.20.20.7 peer-group K8S-METALLB
 neighbor 10.20.20.8 peer-group K8S-METALLB
 !
 address-family ipv4 unicast
  neighbor K8S-METALLB activate
  neighbor K8S-METALLB soft-reconfiguration inbound
  neighbor K8S-METALLB route-map METALLB-IN in
  neighbor K8S-METALLB route-map METALLB-OUT out
 exit-address-family
!
exit
!
ip prefix-list METALLB-SVC seq 5 permit 10.30.0.0/24 le 32
!
route-map METALLB-IN permit 10
 match ip address prefix-list METALLB-SVC
exit
!
route-map METALLB-OUT deny 10
exit
