---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  # List any repositories that Renovate should
  # run against, in the form of `USER/REPO`
  config.json: |-
    {
      "repositories": [
        "rciliberto/lab-gitops"
      ]
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  # Note: You can change this to any schedule in cron syntax, or keywords like `@hourly`
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:43.204.0
              name: renovate-bot
              env:
                - name: RENOVATE_PLATFORM
                  value: github
                - name: RENOVATE_GIT_AUTHOR
                  value: 'Renovate Bot <bot@renovateapp.com>'
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env-prod
                      key: RENOVATE_TOKEN
                - name: GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env-prod
                      key: GITHUB_COM_TOKEN
                - name: RENOVATE_AUTODISCOVER
                  value: 'false'
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: info
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}