apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:rciliberto/lab-gitops.git
        revision: main
        directories:
          - path: apps/tenants/*
  template:
    metadata:
      name: '{{ `{{ .path.basename }}` }}'
    spec:
      project: tenants
      source:
        repoURL: git@github.com:rciliberto/lab-gitops.git
        path: '{{ `{{ .path.path }}` }}'
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{ .path.basename }}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
