---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-relay
  namespace: smtp-relay
spec:
  encryptedData:
    smtp-relay-password: AgCFw8SPNkk578nXkcq30GNeaKAXhvDcOcBV9Fyur2Fk4yQ2znfhTk0sHavHmkrSRo/KAKZxbKvZaFztGwAnGyAtSH//hWwLLTpbcxon9Uz0eWdqJtt0Ro3iptMOQq8BXEpamwBQpY6jJ0J8B2NR4KDbg7RqC3Pe9gVyP9HBxWcQT1QuJe4mZoQGVWQhZ3y2STwH9a+8a1bJ8Gw50e6G+2fjXKT50T3wIhD5s5dWQsp8Ryy/JyqX4zafbDJLqyiRse9gAs9ujFxFYcUnGGXGVQ5Y6c/fqwR3+jkJNX4fouEFw2vsuIWu41k32vg/aJzxps3MfUEn/WqD0hP8dXNWzfyBnfuswgfeVBLlq+aKJQWTwo431IGOFnA7P0NgRLUm4j9zMyC4N5dV/xAbSoAqySJl/P5SKld3OkOi3aXKD9A3JNj6FVRIuCbms1KcWgqIbTq2T1ul5by8Z7Mij8v9zOWRq2MNWxOfijH1XbfKyBacMHzzBXymF/1s3lh7Z74i51Qzfy/FM7Fi7Sy6t7cbIdCCNEculrwzAq0buV5vLRAqQi9Df2Br+yncBPbX/y8IFGNhgh8lM0eF9Lqy0RdgCQLQOeKnMdc/TvMPnysMoNM1KTGEbpqEvDlMW2uMQ5t/yCEPCu2Vo84hFc51U3UxeWkIFsksEMwxPtJqJQOGxdKDCww5by77AXD9+f9+IzfRxtxOBFRVufLy/kOfWWP7TkxSJldmkfuXgFTVgmKa3WKjXsZRUcMwatP+DxA9UlFcd+uw2w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: smtp-relay
      name: smtp-relay
      namespace: smtp-relay
