---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-relay-secret
  namespace: smtp-relay
spec:
  encryptedData:
    smtp-relay-password: AgBYR1oNdXjhJ7bK0avvv5ZSewrIUu8G/2Q+/LKlxJ7bLAzzgCSN0Z9a3VfE0fmOwxQreifp9BqnLGgwCnrDm47lxaxxUlBg28dn22LfRYGWYEGTyLrZrvvO7fNoO/6v0c22z/p/ZO5WHhqKgaeT53/RjYoc4GP1/mu9CJafsYY78FdpJfNMpKWU2ijKCjLHkJmpvSs7uePid2zJUFl9QtiIh0DAs56wY/VX5XG/P50Kvmu7T5RouR+8IRUX6rVndahl3Zun7o5cppSMmYo3mNuDqtMLbVp/Gq0vbY1KbaWG2dXx/7deo8NS9yscwRQtzGlTb+mY4oFGpCTNHUtPkecEAeFHsrSXowYAWr/D5CHFaZbeSmPW9Ora2R/sYI2f16XdDsR7VjwsAFUK9Ihbb0cW2n6ywEPxW8mufQEvgdCAXP4S7I0irdH46q7smyDbzg6EoeNZZd8r2Wu1mko63z6WcGxyLYCb78SyJO7smQ1lhbq2jRTNBrmeiE56SnKJcMdCy/j3T8MEohLey+NHlIBIttEMLdTgpMmGkksklmjln+2xVS42YJt92VknpneV7F2kzG/RmubOEbhVNj2U7y6XQK5W3imf2qicLJPZU3qWdD3V5oV9O55b1LjBHrGKFl8xfszk50CQsMTlXCVkXsAv9olNrIu3aGqVyycPBfH/529C390LLRPgmwFKKfA/Efepr+NItQbwElmFtvSPegN3y/C+QtUFHDp2Ohhp2zOgPAH8/Kxp7oME9lvldOWZBoZNEQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: smtp-relay
      name: smtp-relay-secret
      namespace: smtp-relay
