argo-cd:
  createClusterRoles: true
  crds:
    install: true
  redis-ha:
    enabled: true
  server:
    extraArgs:
      - --insecure
    autoscaling:
      enabled: true
      minReplicas: 2
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
  applicationSet:
    replicas: 2